name: Wish
version: '1.0'
main: imperatrix.wish.Wish
api-version: '1.20'
authors: [ mrlamaker ]
description: Wish Gacha Plugin
website: https://mrlamaker.cloud/shop
commands:
  wish:
    description: Base command for crate management
    aliases: [wishes, wish, wi]
